---
  - name: install avahi-daemon
    apt: name=avahi-daemon state={{ pkg_state }}

  - name: update nsswitch.conf
    lineinfile: dest=/etc/nsswitch.conf state=present backup=yes regexp='^hosts:' 
                line='hosts:          files mdns4_minimal [NOTFOUND=return] dns mdns4'
